apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-with-init
  template:
    metadata:
      labels:
        app: nginx-with-init
    spec:
      initContainers:
      - name: wait-for-service
        image: busybox
        command: ['sh', '-c', 'until nslookup nginx-svc.default.svc.cluster.local; do echo waiting for nginx-svc; sleep 2; done']
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
